/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthRostersIndexImport } from './routes/_auth/rosters/index'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const AuthProfileLazyImport = createFileRoute('/_auth/profile')()
const AuthDashboardLazyImport = createFileRoute('/_auth/dashboard')()
const AuthLocationsIndexLazyImport = createFileRoute('/_auth/locations/')()
const AuthUsersCreateLazyImport = createFileRoute('/_auth/users/create')()
const AuthRostersIdLazyImport = createFileRoute('/_auth/rosters/$id')()
const AuthUsersSearchEditIndexLazyImport = createFileRoute(
  '/_auth/users/search-edit/',
)()
const AuthUsersSearchEditUseridLazyImport = createFileRoute(
  '/_auth/users/search-edit/$userid',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthProfileLazyRoute = AuthProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/profile.lazy').then((d) => d.Route))

const AuthDashboardLazyRoute = AuthDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/dashboard.lazy').then((d) => d.Route),
)

const AuthLocationsIndexLazyRoute = AuthLocationsIndexLazyImport.update({
  path: '/locations/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/locations/index.lazy').then((d) => d.Route),
)

const AuthRostersIndexRoute = AuthRostersIndexImport.update({
  path: '/rosters/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/rosters/index.lazy').then((d) => d.Route),
)

const AuthUsersCreateLazyRoute = AuthUsersCreateLazyImport.update({
  path: '/users/create',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/users/create.lazy').then((d) => d.Route),
)

const AuthRostersIdLazyRoute = AuthRostersIdLazyImport.update({
  path: '/rosters/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/rosters/$id.lazy').then((d) => d.Route),
)

const AuthUsersSearchEditIndexLazyRoute =
  AuthUsersSearchEditIndexLazyImport.update({
    path: '/users/search-edit/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/users/search-edit.index.lazy').then((d) => d.Route),
  )

const AuthUsersSearchEditUseridLazyRoute =
  AuthUsersSearchEditUseridLazyImport.update({
    path: '/users/search-edit/$userid',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/users/search-edit.$userid.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      preLoaderRoute: typeof AuthDashboardLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile': {
      preLoaderRoute: typeof AuthProfileLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rosters/$id': {
      preLoaderRoute: typeof AuthRostersIdLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/create': {
      preLoaderRoute: typeof AuthUsersCreateLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rosters/': {
      preLoaderRoute: typeof AuthRostersIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/locations/': {
      preLoaderRoute: typeof AuthLocationsIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/search-edit/$userid': {
      preLoaderRoute: typeof AuthUsersSearchEditUseridLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/search-edit/': {
      preLoaderRoute: typeof AuthUsersSearchEditIndexLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AuthRoute.addChildren([
    AuthDashboardLazyRoute,
    AuthProfileLazyRoute,
    AuthRostersIdLazyRoute,
    AuthUsersCreateLazyRoute,
    AuthRostersIndexRoute,
    AuthLocationsIndexLazyRoute,
    AuthUsersSearchEditUseridLazyRoute,
    AuthUsersSearchEditIndexLazyRoute,
  ]),
  LoginLazyRoute,
])

/* prettier-ignore-end */
